src/apps/accounts/urls.py
from django.conf.urls import url

from products.views import UserProductHistoryView

from .views import (
    acount_home_view,
    AccountHomeView,
    AccountEmailActivateView,
    UserDetailUpdateView,
    )

urlpatterns = [
    url(r'^test/$', acount_home_view, name='test'),
    url(r'^details/$', UserDetailUpdateView.as_view(), name='user-update'),
    url(r'^history/products/$', UserProductHistoryView.as_view(), name='user-product-history'),
    url(r'^$', AccountHomeView.as_view(), name='home'),
    url(r'^email/confirm/(?P<key>[0-9A-Za-z]+)/$', AccountEmailActivateView.as_view(), name='email-activate'),
    url(r'^email/resend-activation/$', AccountEmailActivateView.as_view(), name='resend-activation'),
]

# account/email/confirm/fadsklfklj/ -> activation view

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView

# from products.views import (
#     ProductListView,
#     product_list_view, 
#     ProductDetailView,
#     ProductDetailSlugView,
#     product_detail_view,
#     ProductFeaturedListView,
#     ProductFeaturedDetailView,
#     )

# from apps.accounts.views import # guest_register_view, login_page, register_page
from apps.accounts.views import RegisterView, LoginView, GuestRegisterView
from apps.addresses.views import checkout_address_create_view, checkout_address_reuse_view
from apps.analytics.views import SalesView, SalesAjaxView
from apps.billing.views import payment_method_view, payment_method_createview
from apps.carts.views import cart_detail_api_view
from apps.marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from apps.orders.views import LibraryView
from .views import home_page, about_page, contact_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

    # url(r'^login/$', login_page, name='login'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    # url(r'^register/$', register_page, name='register'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^account/', include("apps.accounts.urls", namespace='account')),
    # url(r'^accounts/', RedirectView.as_view(url='/account')),
    url(r'^accounts/', include("apps.accounts.passwords.urls")),

    url(r'^analytics/sales/data/', SalesAjaxView.as_view(), name='sales-analytics-data'),
    url(r'^analytics/sales/', SalesView.as_view(), name='sales-analytics'),

    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),

    url(r'^api/cart/', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include("apps.carts.urls", namespace='cart')),

    url(r'^bootstrap/$', TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^orders/', include("apps.orders.urls", namespace='orders')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),

    # url(r'^featured/$', ProductFeaturedListView.as_view()),
    # url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),
    # url(r'^products/$', ProductListView.as_view()),
    # url(r'^products-fbv/$', product_list_view),
    # #url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
    # url(r'^products/(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view()),
    # url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),

    url(r'^library/', LibraryView.as_view(), name='library'),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^settings/', RedirectView.as_view(url='/account')),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^admin/', admin.site.urls),
]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.conf.urls import url

from .views import (
    ProductListView,
    ProductDetailSlugView,
    ProductDownloadView,
    )

urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', ProductDownloadView.as_view(), name='download'),
]

src/search/urls.py
from django.conf.urls import url

from .views import (
    SearchProductView
    )

urlpatterns = [
    url(r'^$', SearchProductView.as_view(), name='query'),
]

src/templates/base/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

<!-- Foneawesome CSS -->
<!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">


<!-- jquery confirm css -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">

<!-- Custom Stripe Styling -->
<link rel="stylesheet" href="{% static 'css/stripe-custom-style.css' %}">

src/templates/base/forms.html
{% extends "base.html" %}

{% block content %}
<div class='col-12 col-md-6 mx-auto'>
    {% if title %}<h1 class='my-3'>{{ title }}</h1>{% endif %}
    <form method='POST' action='{% if action_url %}{{ action_url }}{% endif %}'>
        {% csrf_token %}
        {% if next_url %}
            <input type='hidden' name='next' value='{{ next_url }}' />
        {% endif %}
        {{ form.as_p }}
        <button type='submit' class='btn btn-default'>Submit</button>
    </form>
</div>

{% endblock %}

src/templates/base/js.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!-- slim is missing ajax
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

<!-- jquery confirm js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

<!-- js Render -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jsrender/0.9.90/jsrender.min.js"></script>
{% include 'base/js_templates.html' %}

<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>

<!-- Chart JS -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>

<!-- Django Secure AJAX JS -->
<script src='{% static "js/csrf.ajax.js" %}'></script>

<!-- eCommerce sales data JS -->
<script src='{% static "js/ecommerce.sales.js" %}'></script>

<!-- eCommerce Custom JS -->
<script src='{% static "js/ecommerce.js" %}'></script>

<!-- eCommerce Custom main JS -->
<script src='{% static "js/ecommerce.main.js" %}'></script>

src/templates/base/js_templates.html
{% verbatim %}
<!-- stripe template form -->
	<script id="stripeTemplate" type="text/x-jsrender">
		
		<form class='payment-form' action="" method="post" id="payment-form" data-token='{{:publish_key}}' data-next-url='{{:next_url}}'>
		  <div class="form-row">
		    <label for="card-element">
		      Credit or debit card
		    </label>
		    <div id="card-element" class='form-control'>
		      <!-- A Stripe Element will be inserted here. -->
		    </div>

		    <!-- Used to display form errors. -->
		    <div id="card-errors" role="alert"></div>
		  </div>

		  <button class='btn btn-primary my-3 btn-load'>{{:btn_title}}</button>
		</form>

	</script>
{% endverbatim %}

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_list_url %}
{% url 'about' as about_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url 'account:home' as account_url %}
{% url 'cart:home' as cart_url %}

{% url 'orders:list' as order_list_url %}
{% url 'billing-payment-method' as payment_method_url %}

{% url 'account:user-update' as user_update_url %}
{% url 'password_change' as pw_change_url %}
{% url 'marketing-pref' as market_pref_url %}
{% url 'library' as library_url %}

{% url 'account:user-product-history' as product_hist_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">

	<div class='container'>
	  <a class="navbar-brand" href="{% url 'home' %}">
	  	<img src="https://getbootstrap.com/docs/4.1/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
	  	{% if brand_name %} {{ brand_name }} {% else %} CFE eCommerce {% endif %}
	  </a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item {% if request.path == home_url %}active{% endif %}">
	        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
	        <a class="nav-link" href="{{ products_list_url }}">Products</a>
	      </li>


	      {% if request.user.is_authenticated %}
	      <li class="nav-item dropdown {% if request.path == account_url or request.path == about_url or request.path == contact_url or request.path == order_list_url or request.path == payment_method_url or request.path == user_update_url or request.path == pw_change_url or request.path == market_pref_url or request.path == library_url or request.path == product_hist_url %}active{% endif %}">
	        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          Account
	        </a>
	        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
	          <a class="dropdown-item {% if request.path == account_url %}active{% endif %}" href="{{ account_url }}">Home</a>
	          <a class="dropdown-item {% if request.path == about_url or request.path == contact_url %}active{% endif %}" href="{{ account_url }}#support">Support</a>
	          <a class="dropdown-item {% if request.path == order_list_url or request.path == payment_method_url %}active{% endif %}" href="{{ account_url }}#billing">Billing</a>
	          <a class="dropdown-item {% if request.path == user_update_url or request.path == pw_change_url or request.path == market_pref_url %}active{% endif %}" href="{{ account_url }}#settings">Account Details</a>
	          <a class="dropdown-item {% if request.path == product_hist_url %}active{% endif %}" href="{{ product_hist_url }}">History</a>
	          <a class="dropdown-item {% if request.path == library_url %}active{% endif %}" href="{{ library_url }}">Library</a>
	          <div class="dropdown-divider"></div>
	           <a class="dropdown-item" href="{{ logout_url }}">Logout</a>
	        </div>
	      </li>
	      {% else %}
	      <li class="nav-item {% if request.path == login_url %}active{% endif %}">
	        <a class="nav-link" href="{{ login_url }}">Login</a>
	      </li>
	      <li class="nav-item {% if request.path == register_url %}active{% endif %}">
	        <a class="nav-link" href="{{ register_url }}">Register</a>
	      </li>
	      {% endif %}


	      <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
	        <a class="nav-link" href="{{ cart_url }}">
	        	<span class='navbar-cart-count'>{{ request.session.cart_items }}</span>
	        	<i class="fas fa-shopping-cart"></i>
	        </a>
	      </li>


	      <li class="nav-item">
	        <a class="nav-link disabled" href="#">Disabled</a>
	      </li>
	    </ul>

	    {% include 'search/snippets/search-form.html' %}

	  </div>
	</div>
</nav>